### ISSUE TITLE
The Great Name Discussion

### ISSUE THREAD

**Issue by jonathansick** [arceli/charter#1]
Our working name is Archive of Informal Astronomy Communications. It was coined by @kelle:

> I like Archive of Astronomy Communications. maybe "brief" Astronomy Communications? or even "informal". Yes, after some time with my Thesaurus, I like informal. Archive of Informal Astronomy Communications (AIAC...doesn't quite roll of the tongue but oh well). 
> 
> In particular, I like the word Archive...the primary discovery mechanism for this content is the actual blog...the Zenodo Archive is just the place where we are "filing" the information for safe keeping and indexing. We can hammer out details of optimal article discovery as we go along and as Zenodo matures.

I'm creating this issue as a place where people can either agree on this name or another alternative.

**Comment by jonathansick** [comment]
I had a thought for a name:

**Colloquial Astronomy**

It's short, gets at what we're trying to capture, and doesn't try to define whether it fits in the 'archive' or 'journal' box.

**Comment by owlice** [comment]
I had suggested AltAstro, but ALT should be an acronym... Archive of Literature for (on? about?) Astronomy is all I've been able to come up with, but I have to think there's something better out there!

**Comment by kelle** [comment]
-1 for Colloquial. I think it's pejorative. Like slang. 
-1 for Alt also because I think "alt" has a "not as good" overtone to it. Like, this stuff isnt good enough to be published anywhere else, so it needs to go to an alternative place. 

Archive of Informal Communications about Astronomy...AICA...is that any better? I think it's worse since it adds the "about".

**Comment by owlice** [comment]
Tossing these in more as brainstorming than anything else... 

Astronomy Communications Archive (ACA)
Astronomy Chronicle (or Chronicles)
The Astronomy Files
Astronomy Compendium _or_ Compendium of Astronomy 
Astronomy Digest 

Collection.. repository...

**Comment by kelle** [comment]
I do like the word "archive" and I like "Astronomy" as the first word.
Astronomy Informal Communications Archive?

**Comment by owlice** [comment]
Do we need to worry about confusion with arXiv if we use "archive"? 

I'm tempted now to suggest we call it "Annie" or "Stanley" or some such. :-D

**Comment by davidwhogg** [comment]
Let's call it Archie.  No reason for a prosaic name!

**Comment by owlice** [comment]
Dang! That's perfect!

**Comment by kelle** [comment]
I like Archie but am uncomfortable with its namesakes (Archie Bunker and Archie the comic book). A little google search turned up Arcelia or Araceli. Which, if you believe the baby name sites, means 'alter of the sky'.
http://www.babynamespedia.com/meaning/Arceli
http://www.babynamespedia.com/meaning/Araceli

I'm fine with Archie, but want to also throw this out there for consideration.

**Comment by owlice** [comment]
Well, there was also the archie ftp service and looking at that wikipedia article reminded me of anarchie, which could be another way to go! :-D 

We could probably come up with a (possibly tortured) backronym for it if we wanted to*, but I think it stands on its own without one. 

*or have a contest for the best backronym

**Comment by davidwhogg** [comment]
I love Arceli

**Comment by kelle** [comment]
Arceli - The Archive of Informal Astronomy Communications
usage: "I published it in Arceli." or "in the Arceli archive."
twitter - arceli_archive

**Comment by jonathansick** [comment]
:arrow_up: Love it.

**Comment by owlice** [comment]
Maybe it’ll grow on me. The backronym is excellent; the twitter handle is long. @arceliarc isn’t taken, however.

**Comment by davidwhogg** [comment]
what about http://arce.li?

**Comment by davidwhogg** [comment]
ps don't search that domain -- we should either buy it or not buy it!

**Comment by jonathansick** [comment]
@davidwhogg Are you getting it? I have it up on hover _right now_

**Comment by davidwhogg** [comment]
buy it -- I will pay you back

**Comment by jonathansick** [comment]
:boom: http://arce.li :boom:

Time to get that twitter handle? I can also rename the github org (yay for redirects!).

**Comment by jonathansick** [comment]
Oh sorry, I forgot that @owlice emailed about getting the twitter/gmail handle. Awesome guys! We can stop bike shedding and build this thing! ;) I'll switch the org name now.

**Comment by owlice** [comment]
Please get that twitter handle! I grabbed the other (email and handle) just to not let them slip by (and, ya know, actually do something useful!); we don’t have to use them, and having everything aligned would be great!!
