### ISSUE TITLE
Update the Charter with PressForward Model

### ISSUE THREAD

**Issue by jonathansick** [arceli/charter#10]
Since @libcce and @kelle have had direct contact with PressForward, I think they know a lot more by now than the rest of us about how Arceli will work. Could they revise the charter README document to outline this? This will really help keep everyone on the same page.

Feel free to scrap any existing content that's irrelevant/out of date. Also, mention how it is being run under ScienceBetter.

**Comment by kelle** [comment]
I'm not exactly sure how the workflow will work with both PressForward and Zenodo but I'll try to modify a bit to reflect where PressForward will fit in. I'm not sure if we'll still need communities, for example. I'll understand it more after a go to PressForward meeting in August and I suspect implementing some things either in Zenodo or PressForward will be a major goal of the coding sprint at AAS.

**Comment by kelle** [comment]
started new issue for ScienceBetter role: #11

**Comment by kelle** [comment]
some changes to charter to reflect role of PressForward: 8c3eff62d3f7ea6cc569fd57ab542fdbe48331f9

**Comment by kelle** [comment]
done. 63180b26ebfa7a022fc7ef5f8a9c07f50b70fe63
