### ISSUE TITLE
ScienceBetter role

### ISSUE THREAD

**Issue by kelle** [arceli/charter#11]
Before changing the charter with the role of ScienceBetter, I think it's best to discuss it here. 

Full disclosure: I'm working out all of the details of running a business as I go along. Hard questions and substantive feedback are very welcome. I'm meeting with a lawyer on Tuesday to work out some details and start writing up contracts.

I see ScienceBetter as the home institution of Arceli. It's the place that money can be funneled into and out of. ScienceBetter can hire folks as independent contractors and compensate them for work done on Arceli. 

As the owner of ScienceBetter, I agree to facilitate the money management, negotiate contracts, pay for costs, reimburse expenses, compensate individuals, etc etc. 

It is not necessary for me to stay involved in Arceli in order for ScienceBetter to remain the host institution.

ScienceBetter will take some "overhead". Right now, I envision doing this simply as charging some hours of my time to the Arceli budget for the admin and coordination work.

I will want to add some ScienceBetter branding somewhere. Just like we'll need to add PressForward, Zenodo, ADS, etc.

All of this is flexible and subject to change as ScienceBetter grows and I learn more about how things work.

Thoughts?

**Comment by libcce** [comment]
Hi Kelle,

I was just looking at Authorea (https://www.authorea.com/aboutus) for an
example, would it be more appropriate for you/Science Better to be an
advisor/consultant? That you provide consultant services on top of the base
system (PressForward + Zenodo)?

-Chris

On Sun, Jun 28, 2015 at 12:05 PM, Kelle Cruz notifications@github.com
wrote:

> Before changing the charter with the role of ScienceBetter, I think it's
> best to discuss it here.
> 
> Full disclosure: I'm working out all of the details of running a business
> as I go along. Hard questions and substantive feedback are very welcome.
> I'm meeting with a lawyer on Tuesday to work out some details and start
> writing up contracts.
> 
> I see ScienceBetter as the home institution of Arceli. It's the place that
> money can be funneled into and out of. ScienceBetter can hire folks as
> independent contractors and compensate them for work done on Arceli.
> 
> As the owner of ScienceBetter, I agree to facilitate the money management,
> negotiate contracts, pay for costs, reimburse expenses, compensate
> individuals, etc etc.
> 
> It is not necessary for me to stay involved in Arceli in order for
> ScienceBetter to remain the host institution.
> 
> ScienceBetter will take some "overhead". Right now, I envision doing this
> simply as charging some hours of my time to the Arceli budget for the admin
> and coordination work.
> 
> I will want to add some ScienceBetter branding somewhere. Just like we'll
> need to add PressForward, Zenodo, ADS, etc.
> 
> All of this is flexible and subject to change as ScienceBetter grows and I
> learn more about how things work.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/11.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by kelle** [comment]
Yes, ScienceBetter can providing consulting services to Arceli to help coordinate the team and get the thing built, launched, and maintained. That makes good sense.

but I don't think "consulting" covers the "holding the money" role. I think the word for that is "grant administration". So ScienceBetter will also handle grant administration and management functions as needed.

**Comment by owlice** [comment]
"ScienceBetter will also handle grant administration and management functions as needed."

That sounds right to me. 

Kelle, has ScienceBetter incorporated, and if so, how is it incorporated?

**Comment by kelle** [comment]
Yes. LLC. Will have operating agreement set up in a week or two.

On Sunday, June 28, 2015, owlice notifications@github.com wrote:

> "ScienceBetter will also handle grant administration and management
> functions as needed."
> 
> That sounds right to me.
> 
> Kelle, has ScienceBetter incorporated, and if so, how is it incorporated?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/11#issuecomment-116342348.

## 

kelle
(via iOS)

**Comment by kelle** [comment]
For the PressForward grant, "Chris and the Harvard-Smithsonian Center for Astrophysics will be the institutional sponsor, but will direct all funds to be paid directly to ScienceBetter as the project coordinator."
