### ISSUE TITLE
Web Hosting and Sys Admin

### ISSUE THREAD

**Issue by kelle** [arceli/charter#12]
As I'm quickly learning, running a website is non-trivial. Longterm, who can take care of the back end sys admin? Who is going to be responsible for the web server which hosts arceli?  I can do the front end config of Wordpress and all that but not the backend.

@aaccomazzi , @libcce  - Is this someone on your team can take care of?  Do we want Arceli to actually be hosted on an ADS/CfA server? Or do we want it to keep it separate and purchase a dedicated Linode?

Answers to these question impact my budget request to the PressForward folks. they provide tech support for the use of their software, but no hosting services.

**Comment by libcce** [comment]
My understanding was that PressForward would host the WP instance, with the
upgrades we will make to enable arceli, that if there was a separate WP
site, it would be more for ScienceBetter services. If that isn't the case,
we could host the instance on our end (http://altbibl.io/). We spin up WP
sites quite often for various projects. Kelle, I would think you would want
this under the ScienceBetter umbrella, but we can write into the proposal
the CfA Library hosting service as an alternative?

On Sun, Jun 28, 2015 at 3:30 PM, Kelle Cruz notifications@github.com
wrote:

> As I'm quickly learning, running a website is non-trivial. Longterm, who
> can take care of the back end sys admin? Who is going to be responsible for
> the web server which hosts arceli? I can do the front end config of
> Wordpress and all that but not the backend.
> 
> @aaccomazzi https://github.com/aaccomazzi , @libcce
> https://github.com/libcce - Is this someone on your team can take care
> of? Do we want Arceli to actually be hosted on an ADS/CfA server? Or do we
> want it to keep it separate and purchase a dedicated Linode?
> 
> Answers to these question impact my budget request to the PressForward
> folks. they provide tech support for the use of their software, but no
> hosting services.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/12.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by kelle** [comment]
My understanding was the complete opposite -- that PressFoward just gives us the plugin which we install on our own WP site.

I did a bit of thinking and researching and I agree, it would be ideal if SB could host the site. I'll include this cost in the budget request. 

I have some skills on this front, and a consultant already working on it with a slightly larger skill set, but they are not as strong as I'd like them to be. Does anyone know anyone who would be interested and willing to help out with this? (Not just with Arceli, but with our multi-site configuration needs.) We use an Apache server on Linode.

**Comment by kelle** [comment]
I'm moving forward with hosting arce.li on ScienceBetter. I've also brought on @elambrid to help with the sysadmin. We'll probably be able to have a fresh wordpress install up by the end of the week.

**Comment by libcce** [comment]
Great news about getting arce.li up by the end of the week. I talked to
Stephanie at PressForward this morning. She mentioned that another group
had budgeted $1K for website support, but I think that is over 3 years
(Stephanie said she would supply you with that info).

On Mon, Jun 29, 2015 at 4:30 PM, Kelle Cruz notifications@github.com
wrote:

> I'm moving forward with hosting arce.li on ScienceBetter. I've also
> brought on @elambrid https://github.com/elambrid to help with the
> sysadmin. We'll probably be able to have a fresh wordpress install up by
> the end of the week.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/12#issuecomment-116834444.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by owlice** [comment]
That sounds great!

**Comment by kelle** [comment]
this is all worked out and i've started a new repo for the website
https://github.com/arceli/website
