### ISSUE TITLE
broadening the group - the board?

### ISSUE THREAD

**Issue by kelle** [arceli/charter#13]
I think it's time to broaden the group a bit:
- I'm thinking of reaching out the CSWA to see if someone from their committee would like to join since their blog is a major producer of content.
- I'm thinking of reaching out to John Johnson directly since he also produces a bunch of content
- I reached out @adrn cause I assumed he was on this discussion from the beginning.

Does anyone have any thoughts on what "group" we're forming? Is it the Board of Arceli? And then we will later make an Editorial Board?

**Comment by libcce** [comment]
I think that is correct, sounds like a board to me, if they would like to
join.

On Tue, Jun 30, 2015 at 12:07 PM, Kelle Cruz notifications@github.com
wrote:

> I think it's time to broaden the group a bit:
> - I'm thinking of reaching out the CSWA to see if someone from their
>   committee would like to join since their blog is a major producer of
>   content.
> - I'm thinking of reaching out to John Johnson directly since he also
>   produces a bunch of content
> - I reached out @adrn https://github.com/adrn cause I assumed he was
>   on this discussion from the beginning.
> 
> Does anyone have any thoughts on what "group" we're forming? Is it the
> Board of Arceli? And then we will later make an Editorial Board?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/13.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by jonathansick** [comment]
Having separate administrative and editorial boards seems like a good idea. The job of Arceli Board would roughly be to
- Develop and maintain the technical infrastructure in conjunction with Zenodo/ADS/PressForward partners.
- Promote the service.
- Provide technical assistance.
- Broadly specify the editorial policy and mission of Arceli.
- Select the editorial board, who would make case-by-case editorial decisions.

I think @kelle (ScienceBetter) would be then be permanent Chair of the Arceli Board.

† I'm not a lawyer.

**Comment by kelle** [comment]
Hearing no objections, I will reach out to the CWSA and JJ.

Please rack your brains for nominations to the Board of content creators  
- folks from outside of North America. We could use voices from Australia, UK, Germany.
- folks who create even more non-traditional content than we already have represented...maybe folks who produce visualizations or animations? 

Names coming to my mind are Iva Momcheva (Yale but on the market), Vanessa Moss (Australia), Betsy Mills.

**Comment by owlice** [comment]
How about Sarah Kendrew? 

Do you want to include professional bloggers? The one that comes particularly to mind is Emily Lakdawalla, if not for the board of content creators, perhaps for the editorial board, if that’s something she’d consider. 

Sabine Hossenfelder perhaps? Though she might be more purely physics than astrophysics; anyway, her blog is here: http://backreaction.blogspot.com

**Comment by kelle** [comment]
Julianne Delcanton and Sean Carroll of Cosmic Variance

**Comment by kelle** [comment]
I would vote no to Lakdawalla because her audience is primarily a non-professional one. Prolly same for Sean Carrol.  While Julianne's post, at least the ones I know about, have been targeted to professionals.

**Comment by jonathansick** [comment]
Another great content creator is [Jake VanderPlas](http://jakevdp.github.io), who does really great technical astro-python stuff. Honestly, Jake's writing is the stuff that you _would_ cite in a paper. And someone from the Astrobites leadership? I don't know if you want them on the board, but we certainly would want to work with them.

**Comment by libcce** [comment]
From astrobites, Meredith Rawls or Ellie Newton? +1 for Jake VanderPlas,
Julianne and Sarah.

On Thu, Jul 2, 2015 at 9:45 AM, Jonathan Sick notifications@github.com
wrote:

> Another great content creator is Jake VanderPlas
> http://jakevdp.github.io, who does really great technical astro-python
> stuff. Honestly, Jake's writing is the stuff that you _would_ cite in a
> paper. And someone from the Astrobites leadership? I don't know if you want
> them on the board, but we certainly would want to work with them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/13#issuecomment-118038112.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by kelle** [comment]
invitations sent.

**Comment by mrawls** [comment]
Thanks for the invite, this look like an awesome project! I'd like to suggest inviting Jedidah Isler, Jim Davenport, Lia Corrales, Jennifer Hoffman, and Pauline Barmby to join the board. I'm not sure what the ideal board size is, though, so don't feel compelled to invite all of them.

**Comment by kelle** [comment]
Great names @mrawls! I've already reached out to @eblur. and I agree with @jradavenport. Could you give brief justifications for the others?

**Comment by eblur** [comment]
Is J. Kirkpatrick on here? She would be ideal for consulting on WiA blog posts.  We could use better URM representation, though. So I would second J. Isler or J. Johnson.

**Comment by kelle** [comment]
Invites already sent to both Jessica Kirkpatrick and John Johnson. I appreciate and hear the 2nd for Jedidiah. I'm unfamiliar with her role on the internets...could you expand a little bit on her work that's relevant to the project?

**Comment by jradavenport** [comment]
I'm certainly intrigued, and have been keeping an eye on y'alls discussions about Arceli (has there been a decision on how to pronounce it?)

Looking through this thread, is the proposal to have 2 boards or 3?
- Admin
- Board of content creators
- Editorial board

I can see how each of these might be different, but am always wary of admin-bloat

**Comment by kelle** [comment]
I envision just two boards -- one admin and the other editorial. There very well may be overlap between the two eventually but at this point, I just want folks help out with getting this thing started and shaping the project without having to commit to curating content.

The admin board isn't just content creators, it also includes the library, indexing and archiving side via reps from ASCL ( @owlice), ADS ( @aaccomazzi ) , Zenodo ( @lnielsen ), and CfA Library ( @libcce ). I am just presently trying to expand the board a bit to get some more voices.

**Comment by kelle** [comment]
@skendrew has joined us!

**Comment by skendrew** [comment]
Morning all! Catching up on all the discussion.

**Comment by mrawls** [comment]
@kelle: I recommended all the folks I did because I thought it was a twitter-heavy yet diverse bunch of astronomers at various levels who might be excited about this project. Can't say for sure whether they'd all be ideal board picks, but they are all very active online, likely to be at future AAS meetings, and seem well-poised to benefit from a service like Arceli, so perhaps they'd like to have the opportunity to contribute. No worries if you can't invite them all!

**Comment by kelle** [comment]
@berkeleyjess said yes! She might not start participating until September due to summer travel, but she's on board! Yay!

**Comment by kelle** [comment]
Made a new document: https://github.com/arceli/charter/blob/master/AdminBoard.md
