### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by kelle** [arceli/charter#14]
a logo needs to be made. I have no ideas.

**Comment by libcce** [comment]
To start, you can try a logo generation tool or simply go with text and a nice font. On the other hand, I can ask a graphics design friend at the CfA?

**Comment by jonathansick** [comment]
I just played around with some font treatments at TypeKit... really rough and no kerning... but you can see where a type logo might go. For script faces we'd clean up the ligatures.

![napkin 2 15-07-02 9 33 15 am](https://cloud.githubusercontent.com/assets/349384/8478169/8c09c2e4-209d-11e5-9eb8-d794b9733639.png)

**Comment by jonathansick** [comment]
Another treatment idea: include the RSS logo:

![arceli_logo](https://cloud.githubusercontent.com/assets/349384/8479910/b6ef4820-20a8-11e5-9001-1eea440c8ee4.png)

(Using Futura PT Heavy here)

**Comment by kelle** [comment]
I really like Corner Store...

**Comment by libcce** [comment]
+1 Corner Store... but Jonathan's design is nice as well (with possibly
different font colors)

On Thu, Jul 2, 2015 at 12:26 PM, Kelle Cruz notifications@github.com
wrote:

> I really like Corner Store...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/14#issuecomment-118084766.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by jonathansick** [comment]
Yeah, Corner Store has some good vibes; gives it a friendly, hipster feel, which matches our mission of integrating blogs into the literature. If we want to pursue a hand script look I can mock up more faces. For Corner Store I'd definitely hook up the 'A' and 'r' in Illustrator.
- Preferences on 'Arce.li' vs 'Arceli'?
- Preferences on color? Send me a hex.

**Comment by libcce** [comment]
I vote Arce.li and the color might depend on the WP template, but I'm fine
with Kelle making an executive decision.

On Thu, Jul 2, 2015 at 3:56 PM, Jonathan Sick notifications@github.com
wrote:

> Yeah, Corner Store has some good vibes; gives it a friendly, hipster feel,
> which matches our mission of integrating blogs into the literature. If we
> want to pursue a hand script look I can mock up more faces. For Corner
> Store I'd definitely hook up the 'A' and 'r' in Illustrator.
> - Preferences on 'Arce.li' vs 'Arceli'?
> - Preferences on color? Send me a hex.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/14#issuecomment-118149403.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by kelle** [comment]
I like the dot in there since the URL is non-traditional.
we'll have a lot of control over the color scheme of the WP template so the sky's the limit!
I'm also fine with black for the moment...maybe we start messing around with more colors once have a website to play with...

**Comment by jonathansick** [comment]
Here's what the 'Corner Store' logo looks like when I drew in the Ar ligature:

![corner_store_logo](https://cloud.githubusercontent.com/assets/349384/8499737/bf98a74e-2163-11e5-8432-4be0924b1224.png)

For fun, I added a retro drop shadow. When we go to colour we could put the drop in any colour we like. Going for a silver here in the absence of colour.

![corner_store_logo_drop](https://cloud.githubusercontent.com/assets/349384/8499752/e9e0cce8-2163-11e5-9903-6b9e793486e4.png)

**Comment by jonathansick** [comment]
I put this into a repository at https://github.com/jonathansick/arceli_logo/tree/master I'll move this into the Arceli org once git-lfs is available to all orgs on GitHub.

**Comment by jonathansick** [comment]
![icon](https://cloud.githubusercontent.com/assets/349384/8505882/37b9835e-21c5-11e5-9c12-d9a197e79dec.png)

Just rolling with a square-aspect treatment useable for social profiles. Feel free to go an entirely different direction by the way; just fun to spend a few moments thinking about design.

**Comment by kelle** [comment]
I really like the "retro" dropdown shadow!

I also really like the single A (even though it's a little baseball-y). Maybe we can incorporate an image (maybe RSS?) into it and make it a nice square logo. 

I requested git-lfs for the Arceli org.

**Comment by jonathansick** [comment]
<img src="https://cloud.githubusercontent.com/assets/349384/8536596/8fefd862-2421-11e5-8a9d-e7a001b5d53c.png" alt="Arceli" width="250px" height="250px">

How about this concept? I weaved the A and the outer circle, and did a bit of an homage to the RSS logo. I need to work on colors, of course.

**Comment by owlice** [comment]
I like it!

**Comment by kelle** [comment]
At first, I wasn't sure about the tension between the loop of the A and the circle, but now I kind of like it. It indicates that Arceli is like a lasso going out and aggregating content.

**Comment by LibrarPotter** [comment]
I'm impressed with how it's coming together!  I'm still getting a very
baseball feel from it, but maybe different colors will help? Green perhaps?

**Comment by kelle** [comment]
Can we have a silly version where the A wears a cowboy hat and the A is a rope? :)

**Comment by owlice** [comment]
Please, this!!!

**Comment by kelle** [comment]
@jonathansick  Can you make a directory or new repo with the resources you've made?

**Comment by jonathansick** [comment]
@kelle I just updated my logo repo to include a `png` directory that includes rasters of everything, besides the AI files. https://github.com/jonathansick/arceli_logo/

Sorry for the delay here; I've been super 'distracted' by thesis stuff and getting ready for a move.

**Comment by jonathansick** [comment]
<img src="https://media.githubusercontent.com/media/jonathansick/arceli_logo/master/png/arceli_antenna.png" height=256 width=256>

I tried to backtrack from the baseball look with this one. It's not quite done yet.

**Comment by eblur** [comment]
Looks kind of like a radio tower! Is that the idea? (I do like it)

Thesis comes first, though!

**Comment by jonathansick** [comment]
Exactly, the idea is a radio tower... to evoke broadcasting. I just need to add a 60 degree arc to the top, probably.

**Comment by eblur** [comment]
Food for thought.  

I like the ones where the radio "waves" fade a bit closer to the tower.  I do not like the tower representation in theses images, though...
http://www.123rf.com/photo_10501647_design-of-radio-tower-symbols.html

Here's an old-timey radio logo where the radio waves get thinner as you go out:
http://ak.picdn.net/shutterstock/videos/5724026/preview/stock-footage-black-and-white-old-fashioned-representation-of-radio-broadcasting-its-signal-k-footage.jpg

Also I'm generally a fan of the tower being a little more concave.
https://thefinallap.files.wordpress.com/2012/02/radiowaves.png

BUT obviously it's up to you. So far I think everything looks great. I'm just procrastinating today. :dancer:

**Comment by jonathansick** [comment]
Just saw the rad twitter account. We like the radio tower, @kelle ? Should I focus on improving that design?

**Comment by kelle** [comment]
I do like the radio tower idea for our icon and @eblur's suggestions. :) 
I really like the ideal of having this logo as a complement to the Corner Store drop shadow banner...so making them "match" somehow would be ideal, but I defer to the creative control of the the artist!

**Comment by kelle** [comment]
@jonathansick: Could you put the ones we/you like in a folder in this repo?

**Comment by jradavenport** [comment]
I inverted the colors to improve contrast w/ the default Press Forward theme.

Note however I did a terrible job by just inverting colors using Preview. @jonathansick please feel free to shame me and redo the colors w/ a more professional hand.

![logo_inv_test](https://cloud.githubusercontent.com/assets/3179868/13585018/548e641a-e487-11e5-8414-df7f06ea469d.png)

**Comment by jradavenport** [comment]
It has been widely agreed: we need stickers with the logo or some variant. @jonathansick we nominate you to think about it.

@kelle says she will pay for it. Perfect!
