### ISSUE TITLE
Is Arceli public yet?

### ISSUE THREAD

**Issue by jakevdp** [arceli/charter#15]
I've found myself in conversations with folks about similar ideas... is this effort public yet? Should I bring it up?

**Comment by kelle** [comment]
Personally, I have no problem with pointing people to the charter repo. I don't see any reason to keep this effort under wraps. But I'm also typically on the extreme side of openness.

**Comment by jonathansick** [comment]
If it means preventing people from unnecessarily re-inventing the wheel and duplicating effort until we ship, it's probably a good thing for it to be known, even if we're not making an effort to advertise it yet.
