### ISSUE TITLE
Twitter Handle

### ISSUE THREAD

**Issue by kelle** [arceli/charter#16]
We started to discuss in #1 but I dont think we ever actually got the Twitter.
I'm torn between ArceliAstro and ArceliArchive. ArceliArc is taken. 
Thoughts? 
I'm at a workshop for the next two days and would like to start tweeting about this project.

**Comment by libcce** [comment]
+1 ArceliAstro

**Comment by eblur** [comment]
+1 ArceliArchive

**Comment by mrawls** [comment]
Looks like you already picked, but I like ArceliArchive because it's possible we might expand beyond astronomy one day (right? maybe?)

**Comment by kelle** [comment]
I did pick but it's easy to change.

**Comment by jonathansick** [comment]
I created `@arceli_archive` too in March. I emailed the credentials to the group at that time. I'm totally happy with ArceliArchive though!

**Comment by kelle** [comment]
I prefer sans underscore. Any other opinions?

**Comment by owlice** [comment]
I had grabbed @arceli_arc back on March 14; check email from then for credentials.

**Comment by kelle** [comment]
I'm still liking @AstroArchive the best. Other votes?

**Comment by owlice** [comment]
In general, I think it's better to include the name of the resource itself. I like ArceliArchive better than AstroArchive for that reason. AstroArchive as a name is too generic and wouldn't serve to market the brand name.

arceliastro doesn't seem to be taken if you think "astro" must be included in the Twitter handle.

**Comment by kelle** [comment]
I'm sorry, I mistyped. I meant @ArceliArchive, not @AstroArchive.

**Comment by kelle** [comment]
https://twitter.com/arceliarchive
