### ISSUE TITLE
Arceli -> Zenodo workflow

### ISSUE THREAD

**Issue by kelle** [arceli/charter#18]
Now that the curation process is pretty much functional (via PressForward and Arceli WordPress site), I believe the next step will be getting that curated content into Zenodo. Without knowing what that workflow will look like, it's hard for me to move forward on our WP site. 

Just to be sure we're on the same page, here's my understanding of the workflow we envision:
start with dirty RSS feeds with incomplete meta data
-> Arce.li WP site via PressForward (where we curate & fix up the meta data)
-> import "published" content to Zenodo (need to import images, not just links in addition to text) for proper _archiving_
-> ADS index (with original link and link to zenodo archive)

So, my questions
- What tool exist for importing to Zenodo? Do we need to build something?
- Are we going to be able to publish content on behalf of authors? Basically, We want Arceli to be able to make new records for individual authors.
- what meta data fields are the most important and how do they translate between rss meta fields and zenodo fields? We should get all the major blogs to fix up their feeds so this meta data gets auto imported by PressForward and preserved through the "publishing" process

@lnielsen

**Comment by kelle** [comment]
This convo was kinda started in #5, but that thread is too technical for me. I could use some help figuring out what to do next.

**Comment by kelle** [comment]
I just found a lot of answers to my questions in the Charter: https://github.com/arceli/charter#rest-metadata-guidelines

does anyone know how Zenodo's metadata fields translate into the typical RSS fields? And how our contributing blogs can modify their RSS feeds to include these properly?

**Comment by kelle** [comment]
We can add custom meta data fields to each RSS feed we're ingesting so, we don't need the source blogs to do anything. Maybe I should make custom fields for every feed: `zenodo_<field>` for all the ones listed in the Charter?

**Comment by libcce** [comment]
We will need to crosswalk RSS/PressForward fields to DataCite. Have any sample AstroBetter stories to play with in the Zenodo sandbox http://dev.zenodo.org/ ?
