### ISSUE TITLE
Scheduling Spring Meeting

### ISSUE THREAD

**Issue by kelle** [arceli/charter#19]
Chris (@libcee)  would like to start planning our spring meeting in Boston at CfA. March 21-26 is the Python in Astro conference at UW. Maybe week of March 7?

**Comment by libcce** [comment]
Thanks for mentioning https://python-in-astronomy.github.io/index_2016.html, might be something I send @dbouquin to! For the meeting here, the week of March 7 sounds good. Plus, I like the idea of having ahead of Python in Astro.

**Comment by mrawls** [comment]
Perhaps I missed it, but are we still planning a working meeting at/before/after the Winter AAS, as part of hack day or otherwise? I can't commit to a trip in March yet, but I'll pencil in the week of the 7th and see.

**Comment by kelle** [comment]
Yes, we are _also_ planning on working during the Hack Day at AAS...which
is on Friday, Jan 8.

On Mon, Aug 24, 2015 at 2:09 PM, Meredith Rawls notifications@github.com
wrote:

> Perhaps I missed it, but are we still planning a working meeting
> at/before/after the Winter AAS, as part of hack day or otherwise? I can't
> commit to a trip in March yet, but I'll pencil in the week of the 7th and
> see.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/19#issuecomment-134321327.

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by kelle** [comment]
Funds have been awarded so we can move forward with this.

Are we a go for March 7-8? It's on my calendar and looks good.

@libcce -- did you book the library space?

**Comment by libcce** [comment]
Huzzah! Thanks @kelle for this great news! Yes, the space is booked and you can view it here: http://library.cfa.harvard.edu/collaboration. The calendar is at the bottom of the page, just navigate to March and you will see we have the 7th through the 9th booked.

**Comment by jradavenport** [comment]
I'll be at AAS, and could totally come out for the Spring meeting, but am curious: who do we want to attend the spring meeting? All hands who are willing to work?

**Comment by libcce** [comment]
I'm sure at AAS we can determine what needs to be completed at the March meeting but it would be great to have you there @jradavenport.

**Comment by jradavenport** [comment]
Folks still planning to meet March 7-8 at the CfA?

**Comment by kelle** [comment]
Yep!

On Mon, Jan 25, 2016 at 1:52 AM, James Davenport notifications@github.com
wrote:

> Folks still planning to meet March 7-8 at the CfA?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/19#issuecomment-174418632.

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by kelle** [comment]
For those who need travel support, I can buy plane and train tickets.

**Comment by kelle** [comment]
Started new thread for planning logistics.
