### ISSUE TITLE
Pull Model

### ISSUE THREAD

**Issue by jonathansick** [arceli/charter#2]
In the comments of the [original gist](https://gist.github.com/jonathansick/1d3853b9d6a16b525555) @davidwhogg said:

> what about a pull model, in which a blog post gets pulled to Zenodo and DOIed by an author who wants to cite it -- that way we only arxiv and doi the posts that are in fact worthy of citation?

This Issue is to carry over that idea into this repo.

**Comment by kelle** [comment]
We can do both. We can push content from usual suspect sources and also accept nominations (pull) of content on a case-by-case basis.
