### ISSUE TITLE
Planning AAS Travel

### ISSUE THREAD

**Issue by kelle** [arceli/charter#21]
This is a followup to #9 

The grant was approved so we have funds for @lnielsen to come from Switz and for three domestic flights + 1 night hotel + 1 day MIE for AAS in Jan in Orlando. Who needs/wants the support?
@mrawls ?  Someone from @libcce  staff? @owlice ? 

I have a ScienceBetter CC which can be used to book the flights.

**Comment by mrawls** [comment]
I could very much use the support, thank you! Details: I've already booked my AAS227 flight and hotel, I've applied for the Doxsey Prize, and I am in the process of applying for minimal travel funding through my university (to cover at most ~ 50% of my plane+hotel+reg).

**Comment by libcce** [comment]
@dbouquin is the lead Wolbach librarian on the project. @LibrarPotter has been working a great deal on the project already and has worked at CERN with @lnielsen as well. I'd like for both of them to go, did you budget for just one of us? I'm covered, I'm going to AAS already for the Unified Astronomy Thesaurus launch.

**Comment by kelle** [comment]
following up via email.
