### ISSUE TITLE
Metadata Crosswalk

### ISSUE THREAD

**Issue by dbouquin** [arceli/charter#24]
@jonathansick @lnielsen, Me @kelle and @libcce spoke yesterday about an updated workflow for arceli. I've posted the workflow as [issue #23](https://github.com/arceli/charter/issues/23). Here I'm outlining a suggested draft of a potential crosswalk for the metadata we'll be gathering like @libcce  mentioned in [issue #18](https://github.com/arceli/charter/issues/18#issuecomment-131656236).
Some of the elements are missing from the PressForward column but they may be available as added "custom fields" in the plugin. These elements could be used to create an adequate blog type citation.

| PressForward | Zenodo | ADS |
| --- | --- | --- |
| item_author | creators->creator->creatorName | %A Author List |
| manual entry needed | creators->creator->affiliation | %F Author Affiliation |
| source_title | titles->title | %T Title (required) |
| revertible_feed_text | descriptions->description(descriptionType=Abstract) | %B Abstract Text |
| item_date | dates->date(dateType=Issued) | %D Publication Date |
| manual entry needed | rightsList->rights->rightsURI | %C Abstract Copyright |
| item_tags | subjects->subject | %K Keywords |
| pf_feed_item_source | publisher | %G Origin |
| created by Zenodo | identifier(identifierType=DOI) | %Y DOI |
| [YYYYJJJJJVVVVMPPPPA](http://adsabs.harvard.edu/abs_doc/help_pages/data.html) e.g. 2016arcel15.....10A | created by ADS | %R Bibliographic Code (required) |
| item_link | alternateIdentifiers->alternateIdentifier(alternateIdentifierType=URL) | %U for Electronic Document |
| Mined from body text of blog | relatedIdentifier(relatedIdentifierType=URL | %Z References |

And these are additional fields in the ADS which can be included:

%X Comment (equivalent is miscellaneous & is searchable in ADS)
%M Language (if not English)
%t Original Language Title
%O Object Name
%W Database (if submitting for more than one) e.g. astro, physics

**Comment by dbouquin** [comment]
[ADS Help Pages](http://adsabs.harvard.edu/abs_doc/help_pages/adshelp.pdf)\- Refer to the section 6.5: The ADS Tagged Format for ADS elements

**Comment by AramZS** [comment]
Formal statement of http://jats.nlm.nih.gov/publishing/1.0/

**Comment by AramZS** [comment]
Forming the metadata file and sending it off should be done in wp-cron as a queue so we don't have to force users to leave the page open to send

**Comment by libcce** [comment]
@augustfly can you provide an AAS JATS XML example? Thanks!

**Comment by dbouquin** [comment]
[pressforward class metas](https://github.com/PressForward/pressforward/blob/master/includes/class-pf_metas.php#L305)

**Comment by augustfly** [comment]
just to be clear @libcce we aren't over to JATS yet. I have NLM v2.3.  If you really want a JATS example then I can get you an elife or peerj source XML instead.

**Comment by libcce** [comment]
elife JATS https://github.com/elifesciences/JATs-xml

**Comment by augustfly** [comment]
exactly

**Comment by AramZS** [comment]
isIdenticalTo - Arce.li URL is sent in that field to indicate it archive the original? Maybe that translates to another %U?

**Comment by AramZS** [comment]
Arceli collection will provide bibstem to ADS

The Journal title will need to have [SOURCE_TITLE], Aggregated by Arceli

%G is not to be used. We will use %J - journal_title in Zenodo and that will be used with the Journal title as above.

**Comment by lnielsen** [comment]
https://docs.google.com/spreadsheets/d/1ti2ny9o0_fpA0ZgWe_F6o9ISmBApEjjDRTu0P7XLRd4/edit?usp=sharing
