### ISSUE TITLE
March Meeting Logistics 

### ISSUE THREAD

**Issue by kelle** [arceli/charter#26]
We're planning to meet at the CfA in Cambridge, MA March 7-8 (#19) and it's time to start to making travel arrangements. I'm going to buy my train ticket now...probably to arrive Sunday night and leave Tuesday evening. 

We have the budget to support one more NE corridor train trip and 2 domestic flights. I'd prefer to buy this tickets rather than deal with reimbursements. We also have the budget to support 4 hotel rooms for 2 nights.

@libcce Advice about lodging? Where should we stay?

**Comment by kelle** [comment]
@jonathansick Will you be able to join us? 

@aramzs Can you join us? Want to coordinate taking the same train from NYC?

@lnielsen We're planning on you being able to join us remotely.

@eblur @ernewton @augustfly  If y'all are around Cambridge those two days and interested in helping getting this thing built, please consider joining us!

**Comment by jradavenport** [comment]
I was planning to stay in an AirBnB or similar - if anyone wants to share?

I'll probably arrive Sunday night, and hope to leave Thursday

**Comment by adrn** [comment]
Funny how things work out: I'm giving a seminar at the cfa on the 8th, so I'll be in town March 6-8 and already have travel / accommodations booked. I have other meetings but I'll probably drop in and out of that's cool?

**Comment by kelle** [comment]
Awesome @adrn!! Dropping in and out is fine with me. I think we'll be in the CfA library.

@jradavenport I'm a +1 for the AirBnB.

**Comment by libcce** [comment]
AirBnB is probably the best way to go. Or there are B&Bs in the area. 

FYI, on the 8th, I'm hoping we can combine the Seamless Astronomy mtg w/ the Arceli mtg.

**Comment by kelle** [comment]
@jradavenport Any progress on the AirBnB or should we book rooms? 

This is where I stayed last time: http://www.irvinghouse.com/ but I'm not sure about their availability.

**Comment by jradavenport** [comment]
Nobody else expressed AirBnB interest, so doesn't seem worth trying to coordinate. I'm going to just book something today for myself.

Will check out Irving House though!

**Comment by kelle** [comment]
just booked there.

On Tue, Feb 16, 2016 at 1:16 PM, James Davenport notifications@github.com
wrote:

> Nobody else expressed AirBnB interest, so doesn't seem worth trying to
> coordinate. I'm going to just book something today for myself.
> 
> Will check out Irving House though!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/26#issuecomment-184807751.

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by kelle** [comment]
We're planning on starting tmrw at 9/9:30 tmrw morning in the CfA library.
I've ordered bagels, coffee, and OJ.

On Tuesday, February 16, 2016, Kelle Cruz kellecruz@gmail.com wrote:

> just booked there.
> 
> On Tue, Feb 16, 2016 at 1:16 PM, James Davenport <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Nobody else expressed AirBnB interest, so doesn't seem worth trying to
> > coordinate. I'm going to just book something today for myself.
> > 
> > Will check out Irving House though!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arceli/charter/issues/26#issuecomment-184807751.
> 
> ## 
> 
> Kelle Cruz, PhD — http://kellecruz.com/
> 917.725.1334 — Hunter: x16486 — AMNH: x3404

## 

kelle
(via iOS)
