### ISSUE TITLE
Next meeting - dot Astronomy?

### ISSUE THREAD

**Issue by jradavenport** [arceli/charter#35]
Attn: @arceli/all 

Who is planning to be at .astro8?

Should we have another meetup _before_ June?

**Comment by dbouquin** [comment]
I'll be at .astro and am in favor or another meeting before June.

**Comment by kelle** [comment]
I will also be at DotAstro.

I could also be up for another meeting before June. Maybe NYC in April?
It’ll be gorgeous. Finding housing will be challenging. Only downside I see
is proximity to ADS.

On Tue, Mar 8, 2016 at 3:39 PM, Daina Bouquin notifications@github.com
wrote:

> I'll be at .astro and am in favor or another meeting before June.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/35#issuecomment-193957899.

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by libcce** [comment]
Being on call via Skype worked well (ie Lars), so it could be an option for @aaccomazzi. April is a bit of a crazy time for @dbouquin and I, so we may have to do Skype as well, depending on the dates.

**Comment by kelle** [comment]
if a non-critical mass can come to down to NYC then i’d rather we try to
come up to CfA.

On Wed, Mar 9, 2016 at 9:29 AM, Chris Erdmann notifications@github.com
wrote:

> Being on call via Skype worked well (ie Lars), so it could be an option
> for @aaccomazzi https://github.com/aaccomazzi. April is a bit of a
> crazy time for @dbouquin https://github.com/dbouquin and I, so we may
> have to do Skype as well, depending on the dates.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/35#issuecomment-194319380.

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by aaccomazzi** [comment]
My schedule gets crazy the second part of April, but I'm not sure my presence is essential at this point.  I think y'all should pick dates and I'll try to skype in if feasible.

**Comment by kelle** [comment]
I'm continuing to meet with Aram to push on things. however, due to my other commitments, I am unable to organize another meeting before DotAstro.
