### ISSUE TITLE
Mission statement

### ISSUE THREAD

**Issue by LibrarPotter** [arceli/charter#39]
Although we have an about section and several places in which we describe our goals, I can't find a concise mission statement for arceli.  Does one already exist somewhere that I could add to our website? Otherwise, I'd like to propose that we brainstorm something simple to add.

**Comment by kelle** [comment]
Is this not what you’re looking for?
The Arceli Project is publishing online astronomy content. Arceli serves as
a bridge between blog entries and the Astrophysics Data System (ADS)
https://ui.adsabs.harvard.edu/# so authors can give and receive credit
for their informal scholarly contributions to the field.

It’s here: http://arce.li/about/
We worked on it at he Hack Day in January.

If you think we can do better, I’m happy to try!

On Tue, Apr 19, 2016 at 11:55 AM, LibrarPotter notifications@github.com
wrote:

> Although we have an about section and several places in which we describe
> our goals, I can't find a concise mission statement for arceli. Does one
> already exist somewhere that I could add to our website? Otherwise, I'd
> like to propose that we brainstorm something simple to add.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/39

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by LibrarPotter** [comment]
To me that reads as summing up what we do but not really our goal. Perhaps I'm splitting hairs here, but I was thinking of the mission being more along the lines of:

The Arceli Project publishes informal, scholarly, astronomy content to create a bridge between grey literature (such as blogs) and the formal corpus of scientific publications in the Astrophysics Data System (ADS) in order to allow authors to give and receive credit for their contributions to the discipline and to preserve this scholarship for future use.

**Comment by kelle** [comment]
I like it! And agree, it reads with more gravitas. :)

Do you have the access you need to update the About page?

On Tue, Apr 19, 2016 at 12:53 PM, LibrarPotter notifications@github.com
wrote:

> To me that reads as summing up what we do but not really our goal. Perhaps
> I'm splitting hairs here, but I was thinking of the mission being more
> along the lines of:
> 
> The Arceli Project publishes informal, scholarly, astronomy content to
> create a bridge between grey literature (such as blogs) and the formal
> corpus of scientific publications in the Astrophysics Data System (ADS) in
> order to allow authors to give and receive credit for their contributions
> to the discipline and to preserve this scholarship for future use.
> 
> Or something along those lines.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/39#issuecomment-212013612

## 

Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by LibrarPotter** [comment]
I still have access to updating the About page.  I have added this as our mission statement.  Feel free to change it as you see fit.
