### ISSUE TITLE
Next Meeting: Jan 11-12, 2017 AAS 231 in National Harbor, MD

### ISSUE THREAD

**Issue by kelle** [arceli/charter#42]
Hey @arceli/all,

@AramZS and I have been making progress on this project slowly but surely! We're planning to have the workflow to Zenodo working by the upcoming AAS Meeting and I'd like to try to make a push on this project then. I'm thinking have a coordination meeting on Thursday Jan 11 afternoon/evening and then really get some shit done during the Hack Day on Friday, Jan 12. 

Who's interested/can make it?  Travel budget is available if it will make a difference. 

Early registration for the meeting ends *this* Wed: https://aas.org/meetings/aas231/registration

Kelle

**Comment by dbouquin** [comment]
Sounds good to me. And @katieefrey and I will definitely be there.

**Comment by jradavenport** [comment]
I'm very happy to chat about this @ AAS, and the Hack Day would be a great
time for it!

-Jim Davenport

**Comment by kelle** [comment]
Pinging on this issue. Let's use it to keep a log of what we work on today.

**Comment by kelle** [comment]
Kelle is adding more feeds to the wordpress, Eric Brownwell (SAO) is editing the meta data functions in the php code, @AramZS is troubleshooting the Zenodo workflow.

**Comment by owlice** [comment]
Alice is following progress with great interest!!!! This is an excellent project, and will be a great addition to the community!!!

**Comment by kelle** [comment]
Summary
# The homepage
http://arce.li/
- Added a bunch of blogs to be ingested
# The project github
https://github.com/arceli/
- Updated issue with progress and add some topics for discussion
             - #43 
             - #44
# The custom Wordpress plugin
https://github.com/PressForward/PF_Zenodo
- Documented meta data end points - first github commit and Pull Request!!!
- Made commits and found really important bugs!
# Left to do
- troubleshoot upload process. It's still not doing exactly what we need. 
   - JATS file was not being attached.
   - automate the adding of the post to the Arceli community on Zenodo
