### ISSUE TITLE
relation to ACI Scholarly Blog Index

### ISSUE THREAD

**Issue by kelle** [arceli/charter#8]
We should be aware of this similar but different thing:
http://scholar.aci.info/

I don't have time to put together all the ways it's similar but different but did want to put it on the radar of this group. Well, for one, they are for-profit and have some kind of thing they are selling. But maybe there are things we can use to learn from and help define ourselves...what to do, and also what not to do. 

From their About page:

> Founded in 2004 as Newstex, today ACI Information Group is the world’s leading aggregator of editorially selected and curated social media publications.
> Our focus is simple
> Identify and license authoritative social media publications authored by professionals in the academic, corporate, government, and nonprofit sectors.
> Our promise is powerful
> Provide professionals, researchers, scholars and students with an editorially selected and curated collection of social media publications that provide relevant insights, analysis, and research unavailable in traditional media and journals.

**Comment by owlice** [comment]
Interesting; thanks, Kelle. That’s a nice find! Anyone can search this index for free; I sampled from 50 pages returned in a search for “astronomy” and found posts from Astronomy Computing Today, Astrobites, Hogg’s Research, AAS, Women in Astronomy, Fraser Cain, Phil Plait, etc. Screen shots showing a list of top publications, countries, and institutions (of which Astrobetter is one). 

It has some very nice features, including a summary, a link to the original post, information on the author and publication/source, date of publication, citation creation (there must be a better term for this), bookmarking, “community activity”, the ability to comment, and more. Sample entry. 

Alice

**Comment by owlice** [comment]
Ah, emailed links/images don't appear, so here they are. 

Sample entry: http://scholar.acindex.com/view/1429b46f3622add0104/1471d9b25312528014d

Images: 
![screen shot 2015-04-11 at 12 00 28 pm](https://cloud.githubusercontent.com/assets/3407433/7103079/196a45ba-e065-11e4-8767-ae87d4c0c84b.png)
![screen shot 2015-04-11 at 12 00 07 pm](https://cloud.githubusercontent.com/assets/3407433/7103080/1970c44e-e065-11e4-9eff-146ad5c3bc82.png)
![screen shot 2015-04-11 at 11 59 55 am](https://cloud.githubusercontent.com/assets/3407433/7103081/1975a194-e065-11e4-8d4b-60625b317929.png)
