### ISSUE TITLE
PressForward grant and Funding for Coordination and Code Sprint at AAS in Jan

### ISSUE THREAD

**Issue by kelle** [arceli/charter#9]
I just had a productive chat with Stephanie of Press Forward. They are very supportive of the idea of "awarding" us with ~$10k of their Sloan funds to support the coordination and development of Arceli using PressForward. PressForward is essentially a WordPress theme which enables us to "curate" ingested blog content (via RSS) into a "journal". We use PressForward as the thing to curate the content and to publish the journal's website. It's pretty much perfect for what we want to do.

Also, PressForward will provide us to dev help to incorporate the Zenodo and ADS workflows. And access to the WP front end developer to make the site look the way we want. Again, this is pretty much amazing.

The development which we need to do is adding the Zenodo and ADS workflow.  And figuring out how to archive the content...we still need to figure out if we take in the source HTML, PDFS, or what not.

After discussion with @libcce, we decided that what we could use the $10k for is to support a coordination meeting and coding sprint at the January AAS meeting in Orlando. The $10k can be used to support the travel of participants (~round trip airfare + 1 night lodging + 1 day MIE) and compensation for dev and admin time. We can use it to for our travel, and to bring Lars (of Zenodo to AAS), and for anyone (who is able to work legally in the US) who would like some compensation for their time devoted to this project.  (ScienceBetter would hire you as an independent contractor.)

The idea that Chris and I have is for ScienceBetter Consulting to the the "awardee". We give PressForward a reasonable budget in the neighborhood of $10k, they simply cut a check for the total (!!) and then we use it as we see fit. They do not require any further justification of expenses (!!).  I will put the $10k into the ScienceBetter checking account and then use the ScienceBetter credit card to buy y'alls travel. (I'd rather to do it this way rather than do reimbursements, but this can be discussed.)

From my point of view, two big questions

1) Are y'all ok with Arceli coming under the ScienceBetter Consulting, LLC umbrella? IMO, this is ideal cause it means you (those of you who are able to work legally in the US, at least) can get paid as a consultant for work on this project and we don't have to deal with admin hassles at any given institution.

2) Who wants to go to AAS and commit to working on Arceli for a ~1 hour coordination meeting and to participate in Arceli development during the Hack Day? (It docent have to be your only hack, but you need to be at the Hack Day for the whole thing.)

**Comment by kelle** [comment]
PressForward needs a letter of commitment and a budget request by July 1. So your response is requested ASAP.

**Comment by aaccomazzi** [comment]
As far as I'm concerned, I'm happy to facilitate ADS inclusion but don't want/need any $$ (ok you can buy me lunch at AAS if you insist but that's it).  Assuming hack day does not pose a conflict with other events, I should be able to attend and bring somebody who can actually get work done.

**Comment by jonathansick** [comment]
Hey!

> 1) Are y'all ok with Arceli coming under the ScienceBetter Consulting, LLC umbrella? IMO, this is ideal cause it means you (those of you who are able to work legally in the US, at least) can get paid as a consultant for work on this project and we don't have to deal with admin hassles at any given institution.

I'm okay with this arrangement. As long as I don't hear objections from other people wanting it to be organized differently, I can transfer control of the http://arce.li domain to ScienceBetter. You'll want to budget for the domain (about $16/yr from Hover at least). We might also want to budget for `*@are.li` emails. I honestly don't know who the best provider is for email. Fast Mail? Does Google offer white-label email?

> 2) Who wants to go to AAS and commit to working on Arceli for a ~1 hour coordination meeting and to participate in Arceli development during the Hack Day? (It docent have to be your only hack, but you need to be at the Hack Day for the whole thing.)

I will certainly be at AAS and the hack day and will want to help out. However, I can't answer yes/no regarding funding quite yet. I should have an answer from _my people_ by Monday/Tuesday. Most likely the money might be better directed to someone living off a research grant.

**Comment by jonathansick** [comment]
This may be better directed for a separate issue, but is the PressForward technical arrangement only for WordPress-powered blogs? Do we need separate infrastructure to support other platforms, static blogs, etc?

**Comment by kelle** [comment]
Press Forward can ingest anything with an RSS feed. However, we (the
editors) will interface with it via a wordpress site and the
"journal" content will also be served on the WP site.

On Friday, June 26, 2015, Jonathan Sick notifications@github.com wrote:

> This may be better directed for a separate issue, but is the PressForward
> technical arrangement only for WordPress-powered blogs? Do we need separate
> infrastructure to support other platforms, static blogs, etc?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/9#issuecomment-115909935.

## 

kelle
(via iOS)

**Comment by libcce** [comment]
Yes, I definitely support arceli moving under the ScienceBetter umbrella. The chances were high already that I was going to attend AAS for UAT related activities. My only concern is that the UAT and arceli events don't overlap, but yes, I plan on participating in the arceli AAS event. From my end, we still intend to demo/prototype arceli with AstroBetter being the use case via @LibrarPotter (when she returns from CERN). I'm confident we can do this before AAS.

**Comment by owlice** [comment]
I've been quietly following along, as this all sounds good to me, though I'm curious about the flow of material and its archiving on Zenodo.

I'm happy to attend a meeting and if I can be useful at Hack Day, can likely participate in that as well. (I do know something about WordPress.) Assuming I participate in both and there is room for it in the budget, airfare might be welcome, but I expect to be able to swing a freebie SW ticket by then.

**Comment by lnielsen** [comment]
I'd be happy to participate in the hackday if we can make it work out with the travel support.

**Comment by jonathansick** [comment]
@kelle I just confirmed that I can't accept money under the terms of my work visa, but I'll be at the AAS Hack Day and will offer pro bono services then and at any other time :)

**Comment by kelle** [comment]
Ok, we don't have enough people who need travel support! Can we nominate
some folks pls? Think of other potential bloggers and
producers/editors/curators of content.

I reached out to Ellie Newton who helped put together Astro4Astro, a
similar project.

On Monday, June 29, 2015, Jonathan Sick notifications@github.com wrote:

> @kelle https://github.com/kelle I just confirmed that I can't accept
> money under the terms of my work visa, but I'll be at the AAS Hack Day and
> will offer pro bono services then and at any other time :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/9#issuecomment-116868980.

## 

kelle
(via iOS)

**Comment by owlice** [comment]
Kelle, 

Maybe have a hack event in NYC or Boston some months after AAS for tweaking/improving things? If you don’t have enough takers for AAS funding, some of the funds could go for that. (I found it really helpful to have a small team meet with ADS in Boston to work some things out for the ASCL.)

Alice

**Comment by jonathansick** [comment]
I second @owlice's idea of a Boston meeting because we're sure to need more work to get it running, including cohesive integration with ADS. I wouldn't be conflicted with any AAS+LSST Hack Day duties. I _would_ accept airfare and accommodation for that.

Could we even hold it before AAS?

**Comment by kelle** [comment]
Since we aren't expecting the money until Dec 1, a meeting _after_ AAS makes sense.

**Comment by libcce** [comment]
@kelle, I can add that we may want to fly to the AAS an additional member
of my staff, especially if they will be involved in the AstroBetter use
case, testing of arceli. Alternatively, the Boston idea might be a good
idea as well. We are concerned how these records are ultimately presented
in the NASA ADS. I'll also add, shouldn't you include funding for travel to
George Mason, to work with their developers and to a conference or two for
community outreach purposes? All these sound like valid requests.

On Tue, Jun 30, 2015 at 12:10 PM, Kelle Cruz notifications@github.com
wrote:

> Since we aren't expecting the money until Dec 1, a meeting _after_ AAS
> makes sense.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/9#issuecomment-117240806.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by owlice** [comment]
Yes, after AAS. I think Boston is good because ADS is such an important part of this, and it was hugely helpful to be there and work through different ideas and issues after everything was up and running and cracks and ideas for improvements were evident; some of the necessary work was completed before we left the building, even, because we spent time hacking on things. 

That said (badly/in a wretched paragraph), these other ideas are good, too. I don’t know how much actual conference outreach you’d need to do, though, because the blogosphere/social media spreads news pretty well, and overall, that is the true target for the effort — this effort serves bloggers/content providers (and readers who would like to cite them, but they bring their readers with them).

**Comment by kelle** [comment]
Stephanie has asked us to describe the "in kind" contributions of our time. Could y'all please give 1-2 sentences about what you're willing to commit/already committed uncompensated. Project development, coordination of ADS/Zenodo involvement, implementation of ADS/Zenodo connections, website design, logo design, promotion, etc. (Paging @aaccomazzi @jonathansick @libcce @lnielsen )

**Comment by kelle** [comment]
Please try to also include in your descriptions an approximation of time and cost that you plan to contribute between Dec 2015-Dec 2016. However, I understand that will likely be pure guesswork at this early development stage.

**Comment by libcce** [comment]
From the CfA Library's perspective, we can provide guidance/advice on
curation best practices, limited technical assistance (as we are familiar
with WordPress), and outreach to the community. I'm hesitant to say
commitment to sustainability but we are concerned about it and will help as
much as possible with this aspect.

On Tue, Jul 14, 2015 at 12:19 PM, Kelle Cruz notifications@github.com
wrote:

> Please try to also include in your descriptions an approximation of time
> and cost that you plan to contribute between Dec 2015-Dec 2016. However, I
> understand that will likely be pure guesswork at this early development
> stage.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arceli/charter/issues/9#issuecomment-121295302.

## 

Christopher Erdmann, Head Librarian
Harvard-Smithsonian Center for Astrophysics, John G. Wolbach Library
cerdmann@cfa.harvard.edu | 617-495-7289 | @libcce
_http://library.cfa.harvard.edu/ http://library.cfa.harvard.edu/_
http://orcid.org/0000-0003-2554-180X

**Comment by mrawls** [comment]
Sorry I missed this thread when it started. I am very interested in a post-AAS hack day type work session (maybe even more than one day??), since I plan to attend AAS and could absolutely use the travel support. I can dedicate 100% of my hack day time to Arceli. As you know, I spearheaded the astrobites website overhaul, so I anticipate my biggest contribution in the "make the website look nice with WordPress" area. That includes everything from writing/editing, to layout, to some behind-the-scenes coding, to making a compelling argument for astronomers to use the site in the first place. I can't commit much more than that now, though, since I am working to finish my PhD in 2016.

**Comment by kelle** [comment]
@libcce That sounds awesome! 
- Could you name names please? Or say how many people from your staff will be involved?
- Will you also be able to host and help with logistics and planning of a 2 day Boston-based meeting? Stating that you will be able to provide meeting space at no charge is a significant contribution.

**Comment by adrn** [comment]
Similar to @mrawls (trying to finish phd in 2016, so limited time...), but:
- I'm happy to consult on technical details and devote my time at the AAS hack day
- I'd be willing to help organize / attend other hack days focused on developing the concept and/or technical details
- I'm also willing to provide test content

**Comment by libcce** [comment]
We can host, provide meeting space for a Boston meeting. We will need
advanced notice though, scheduling space can be a nightmare if we are not
fast. As for staff, I have spoken to our Simmons student who is available
to assist. Depending on our needs, additional staff members can assist.

**Comment by jonathansick** [comment]
I've helped with early project coordination, including setting up the GitHub organization, writing up a v0 Charter, securing our domain, securing our Twitter presence and some on-going work with the logo.

In the Dec 2015-Dec 2016 timeframe I'd expect to work on
1. Writing user (publisher) documentation/tutorials.
2. Dog-fooding the RSS publishing route with the up-coming LSST Data Management blog, and refining that workflow as necessary.

I don't know how much time this will be. Certainly a few dedicated hack days and then averaging a couple hours a week on-going as needed.

**Comment by kelle** [comment]
funding request was submitted for 12k to support AAS Hack Day in Jan, spring meeting in Boston, and coordination and operating costs.
